DROP TABLE MACHINE;

CREATE TABLE MACHINE(ID VARCHAR(32), USER VARCHAR(32), CONSTRAINT machine_pk PRIMARY KEY (ID, USER));
INSERT INTO MACHINE (ID, USER) VALUES ('DBE2C1100314005DC830A1', 'JaAlvaro');
INSERT INTO MACHINE (ID, USER) VALUES ('PKWLF018JEW2PZ', 'JaAlvaro');